### ISSUE TITLE
Polybar workpace unclickable

### ISSUE THREAD

**Issue by qkweint** [deter0/xborder#15]
Cannot click polybar workspace module to change workspace with xborder enabled, other modules work as expected.

**Comment by deter0** [comment]
You can use this feature to filter the top:
```
--screen-rect SCREEN_RECT
    The desktop rectangle where you can use the stress toy. Format
    is XxYxWxH (the lower cases x's are required) or WxH where X and
    Y will be 0
````
or you can ```--disable-drag-stress-toy```
