### ISSUE TITLE
too much cpu consumption

### ISSUE THREAD

**Issue by arnavgr** [deter0/xborder#17]
after using xborders my cpu usage goes up to 30% even when no apps are running. is this normal ?\

EDIT: also when i go fullscreen in i3 i can still see the curved borders . How do i fix that?

**Comment by Joachim-42he** [comment]
I have the same problem:

### Setup:
Intel i7-11370H (4 Core, 8 Threads)
TigerLake-LP GT2 [Iris Xe Graphics]
Arch Linux (Endeavour OS), Kernel 5.17.9
 X11
i3
picom

pycairo 1.21.0
xdotool 3.20211022.1-1
gtk3 1:3.24.34-1
gtk4 1:4.6.5-1

### xborders.json:
```
{
  "border-radius": 10,
  "border-width": 5,
  "border-mode": "outside",
  "border-rgba": "FFFF00FF",
  "disable-drag-stress-toy": true
}
```
### Load:
Average Load, with Picom running but without xborder: 0.30
Average Load, after about 30 seconds with xborder running: 1.41
According to htop, whenever xborder is running, there is a single Xorg-Thread consuming 149% CPU.

**Comment by deter0** [comment]
I fixed the fullscreen issue but I can't really do anything about the cpu consumption unless I were to rewrite it without depending on gdk, sorry.

**Comment by Joachim-42he** [comment]
Too bad, but can't be helped, I guess. Thank you anyway.

**Comment by welcoMattic** [comment]
Same here, very high CPU consumption. Too bad, tool was great.

**Comment by SilverTux** [comment]
Hi, my PR #19 aims to solve this issue. If someone could test it on it's system I would appreciate it. On my system I've achieved a 20-25% less CPU usage.

**Comment by deter0** [comment]
Please let me know if this is still an issue @welcoMattic @Joachim-42he @arnavgr

**Comment by welcoMattic** [comment]
`./xborders --help` output:

```
…
ValueError: Namespace Wnck not available
```

**Comment by SilverTux** [comment]
If you run this command what is your output?
`dpkg -l | grep libwnck`

Or if you use a distro which is not debian based then what is your distro?

**Comment by welcoMattic** [comment]
I had to install libwnck on my arch linux. And yes, the CPU consumption is reduced.

**Comment by deter0** [comment]
I've added this to the dependencies are removed xdotools

**Comment by Peloponeso31** [comment]
Preparing a PR, but in short, it is the use of ```self.queue_draw()``` what is causing the performance hit.
```gtk.queue_draw_area(x, y, w, h)``` should be used instead, look at this:

With ```queue_draw```:
![image](https://user-images.githubusercontent.com/32084752/182007839-e7e4663d-022b-4de3-9ded-27fdd6411864.png)

With ```queue_draw_area``` (taking as parameters ```win_data```):
![image](https://user-images.githubusercontent.com/32084752/182007878-4036e404-b6d7-4409-9230-870ca7cadf70.png)

Notice CPU usage and GPU Frequency, in a laptop, fan noise is also cut.

This is not a perfect solution, as it generates artifacts when resizing/anything borders outside the active window:
![image](https://user-images.githubusercontent.com/32084752/182007921-39abe688-8059-4d83-b058-ca98ed522a43.png)

This is a sugestion I've readed here: https://stackoverflow.com/questions/6888965/any-way-to-speed-up-reduce-cpu-usage-when-drawing-with-cairo

**Comment by deter0** [comment]
Closing this since it seems to be resolved!
