### ISSUE TITLE
For compositors that use animations, the border appears before the window does

### ISSUE THREAD

**Issue by alba4k** [deter0/xborder#27]
If a compositor animates the moving of windows, the border appears where the window __will be__, while the window is still moving

![video](https://user-images.githubusercontent.com/84153269/186148963-78e759ad-5ba8-4320-bc65-4c7db510a35a.mp4)

**Comment by deter0** [comment]
Not much I could do about it since the compositor is moving windows on its own and not updating the window positions. You could if there was an api for the compositor, but then you would need to support a lot of compositors and afaik picom doesn't have one.
