### ISSUE TITLE
MPV not framed correctly

### ISSUE THREAD

**Issue by Savanta** [deter0/xborder#31]
MPV leaves small gap left, right, and down and big gap over.
[example](http://0x0.st/o94-.jpg)

**Comment by deter0** [comment]
This is weird because MPV is framed correctly when I run it, even in KDE

![image](https://user-images.githubusercontent.com/82973108/187046992-3076d81a-60cc-4da7-bafa-6c977ae54fa2.png)

**Comment by nimaaskarian** [comment]
I have the same issue with mpv. I'm using i3gaps and pijulius's picom.
