### ISSUE TITLE
top border for Webstorm not aligned with window

### ISSUE THREAD

**Issue by dmolin** [deter0/xborder#33]
This is happening only with Webstorm (and I guess other IntelliJ-based programs; Might be related to Java programs in general?):

When opening webstorm, the top border created by xborder seems to be rendered at an offset of a good 15-20px higher than the window (See image):

![image](https://user-images.githubusercontent.com/861513/186593597-958ddf28-0939-46b8-8b20-31d4405d00b0.png)

I tried using --border-mode inside | outside | center but I still get the same result

WM: i3-gaps-rounded-git, version 4.20.1-98-ga70b89a7

**Comment by deter0** [comment]
This is like #31 but there seems to be 2 different borders?

**Comment by dmolin** [comment]
@deter0 it's actually just one border 😄 

![image](https://user-images.githubusercontent.com/861513/186854668-e85d5b25-6e72-4da2-b624-98414d7761cd.png)

I think the "double" border in the first screenshot was my fault in playing around with xborder (I might've started it twice or something, since I was constantly tweaking and restarting i3 to see if I could get rid of it somehow)

**Comment by dmolin** [comment]
Same issue happening with video player mpv:

![image](https://user-images.githubusercontent.com/861513/191032800-f81d5cbf-08be-4443-af47-2c3530cc5dc4.png)

**Comment by MathisP75** [comment]
It's really Java programs, it does it with a small Java school project I compiled. It also does it with Android Studio.

**Comment by dmolin** [comment]
not to my knowledge @MathisP75 . mpv (the player) is definitely not a Java program (it's written in C) and as you can see from my last comment it does it there too.
