### ISSUE TITLE
Spotify no rounded borders

### ISSUE THREAD

**Issue by DaitiDay** [deter0/xborder#40]
As for the title, the spotify app (AUR package _spotify_) does not have the rounder borders.

**Comment by deter0** [comment]
Weird, works for me. Could you show a video demonstrating this?

**Comment by DaitiDay** [comment]
![14-Sep-22_08-03](https://user-images.githubusercontent.com/58434456/190072462-482de1c3-1225-4a25-9531-69981c156039.png)
![14-Sep-22_08-06](https://user-images.githubusercontent.com/58434456/190072805-df463d62-488d-4678-aab0-538a42bfb901.png)

The "outside" rounded corners are set by the compositor, but as you can see while xborders is adding the inside rouded corners to the terminal, it is not doing the same to spotify (nor for the terminal when it is not focused, but I can live with that)

**Comment by DaitiDay** [comment]
Any update?

**Comment by DaitiDay** [comment]
@deter0 any update?

**Comment by deter0** [comment]
With the merge of #42 does this possibly fix your issue?

**Comment by DaitiDay** [comment]
Yes, it is fixed now 😄 thank you 😄
