### ISSUE TITLE
Re-focusing on a fullscreen window enables xborders

### ISSUE THREAD

**Issue by nimaaskarian** [deter0/xborder#44]
I just saw your commit that fixed the mpv issue, so I installed the new version! 
You added a cool feature (I didn't really check the commits to see if it was intentional tho) that disables xborders when you fullscreen a window (on i3). I really liked it.
But when you switch to another window and switch back to the maximized window, xborders reappears. 
Its a bit annoying in multiple monitor setups, but I can't see xborders using one display or when I have a maximized window on both screens.

Edit: I tested some gtk applications (gVIM, zathura, virt-manager) and I could see the xborders in the corner of them when their window was maximized.

**Comment by deter0** [comment]
It was intentional, but multi-monitor isn't officially supported? Is it working for you?

**Comment by nimaaskarian** [comment]
> It was intentional, but multi-monitor isn't officially supported? Is it working for you?

It isn't? Wow I didn't know becuase it works just fine...
Works like it should, focused window has borders (I use picom as my compositor and xborders works exactly like it). It even worked on my hybrid intel-nvidia setup.

But I encounter this issue with single screen as well : disconnected my second screen, booted up, maximized chromium, switched to another workspace, switch back again on chromiums workspace, and its like this:
![2022-10-15_05-34](https://user-images.githubusercontent.com/88832088/195964489-b5c7b579-320f-412d-a6fd-5314bc2f65f4.png)

(look at the corners, its a bit annoying but its worse with multi monitors)

**Comment by deter0** [comment]
Good to hear it works for you on multi-monitor it works for some people but other people not so much. Anyways, the more recent commit should fix this, can you confirm?

**Comment by nimaaskarian** [comment]
Its working like a charm. Thanks !
