### ISSUE TITLE
[Feature request] Tiling direction indicator

### ISSUE THREAD

**Issue by benthesheep** [deter0/xborder#47]
I've been using XBorder for a while now and I love it but one thing I miss from the standard i3 border is the ability to add a tiling direction indicator to quickly see where a new window will appear when it is opened. It would be a great addition to XBorder!

**Comment by benthesheep** [comment]
I created a rather basic version of a tiling indicator by adding the following:
``` python
from i3ipc import Connection
I3_INDICATOR = True;
INDICATOR_COLOR = [189,77,247,1]
i3 = Connection();
```
Then under the `_draw` function I added this after the border drawing parts:
``` python
if (I3_INDICATOR != False):
            ctx.set_source_rgba(INDICATOR_COLOR[0] / 255, INDICATOR_COLOR[1] / 255, INDICATOR_COLOR[2] / 255, INDICATOR_COLOR[3]);
            parent = i3.get_tree().find_focused().parent;
            ctx.set_line_width(BORDER_WIDTH / 2);
            ctx.new_sub_path();
            if (parent.layout == 'splitv'):
                ctx.move_to(x + w - BORDER_RADIUS, y + h);
                ctx.line_to(x + BORDER_RADIUS, y + h);
            elif (parent.layout == 'splith'):
                ctx.move_to(x + w, y + BORDER_RADIUS);
                ctx.line_to(x + w, y + h - BORDER_RADIUS);
            else:
                pass;
            ctx.close_path();
            ctx.stroke();
        else:
            pass;
```
The problem is this only updates when the active window changes. Ideally it would change when the tiling direction also changes, but from what I've been able to find this is far outside my very limited capability). 

Any help and/or different implementation would be much appreciated!

**Comment by deter0** [comment]
I wish for xborders to be window manager agnostic, so this will not be implemented as it is not standard.
