### ISSUE TITLE
Xborders not launching

### ISSUE THREAD

**Issue by PoweredDeveloper** [deter0/xborder#48]
I use arch
python 3.10.9

on start i have error:
```
Traceback (most recent call last):
   File "/home/dev/Git/xborder/xborders", line 11, in <module>
      import gi
ModuleNotFoundError: No module named 'gi'
```

I tried to install gi using "pip install pgi", but i have an error again

```
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by PoweredDeveloper** [comment]
After hours of searching I finally Solve my problem. If you have this problem check this: 
[PyGObject](https://pygobject.readthedocs.io/en/latest/getting_started.html#arch-getting-started)

**Comment by uzervlad** [comment]
Hi, I'm facing the same problem. How did you fix it?

**Comment by deter0** [comment]
Did you install requirements.txt?

**Comment by ElnuDev** [comment]
If you update to master not having version.txt shouldn't cause errors anymore after #55

**Comment by uzervlad** [comment]
Weird, but reinstalling `requirements.txt` fixed the issue
