### ISSUE TITLE
Add better support for i3

### ISSUE THREAD

**Issue by coloursofnoise** [deter0/xborder#8]
There are some issues with the render position of the outline in i3, especially when using window borders and in tabbed layout.

These can be fixed while also improving performance by making use of the [i3 IPC](https://i3wm.org/docs/ipc.html) to listen to window events and retrieve the focused window dimensions.

I've implemented this in [my fork](https://github.com/coloursofnoise/xborder) along with some other QoL features (custom color, easy install through pip/pipx with feature switches, hide border in fullscreen).
All very hacked together, so I'd be happy to re-implement those as separate PRs here if that's wanted.

**Comment by deter0** [comment]
Hmm, I'll look into it. I didn't know about the pip/pipx stuff I'll give it a shot. If I get time I'll re-implement it since a lot of stuff has changed since the last PR.

**Comment by deter0** [comment]
Now that we're using Wnck thanks to https://github.com/deter0/xborder/pull/19 this shouldn't be an issue

**Comment by coloursofnoise** [comment]
Awesome, thank you! it'd still be great to have the ability to install this through pip (or an AUR package?) but it's really no trouble to hook that up for myself

**Comment by deter0** [comment]
AUR Package is being worked on #20
